### ISSUE TITLE
Fatal Errors On Load With R2API v.2.2.32

### ISSUE THREAD

**Issue by VaelophisNyx** [Jarlyk/JarlykMods#18]
ItemLib causes _HUGE_ error blocks in the console & log, and hard-locks the game at the EA screen.

https://pastebin.com/ujAVf91z
![ss (2019-10-15 at 08 03 20)](https://user-images.githubusercontent.com/1534478/66878341-61168500-ef87-11e9-95af-45d368a0a572.png)
![ss (2019-10-15 at 08 03 34)](https://user-images.githubusercontent.com/1534478/66878343-6378df00-ef87-11e9-97bc-301cfcb277c5.png)

**Comment by Jarlyk** [comment]
Just to follow-up, ItemLib is in the process of being replaced due to breaking changes in the game with the last patch.  The features are being migrated into R2API; once the new release is out, I'll fix the mods.
