### ISSUE TITLE
Give loader's Starter Pack more item.

### ISSUE THREAD

**Issue by CSOLYOO** [Jarlyk/JarlykMods#19]
![1`NZO$U(0OQ~ RGV%GJCF85](https://user-images.githubusercontent.com/20432375/67379400-6ee98d00-f5bb-11e9-98ae-16fa7e9f8d3d.png)
Loader's item

![(~4FV RA{LWPDJD84WVTZ_D](https://user-images.githubusercontent.com/20432375/67379401-701aba00-f5bb-11e9-854a-dd1c1c9bf8f5.png)
REX ‘s item

![YL5PU8CXDTP} HLD}H~3L`4](https://user-images.githubusercontent.com/20432375/67379404-714be700-f5bb-11e9-8dab-b85ac8c42e94.png)
MUL-T ’s item

It's not balance to loader, please give loader some other item!

**Comment by Jarlyk** [comment]
Yeah, I haven't updated it for Loader yet (it just gives the basic speed items).  One suggestion was to make the starter pack configurable and I might also include an optional difficulty slider bump to compensate for the fact that you're starting out with a bunch of items.

**Comment by CSOLYOO** [comment]
Created a Pull Request. Expect the configurable starter pack! Good Job！
