### ISSUE TITLE
How this mod can be played if itemlib blocks the game?

### ISSUE THREAD

**Issue by pO0P3R125** [Jarlyk/JarlykMods#21]
The thing above

**Comment by Jarlyk** [comment]
ItemLib is broken, due to the recent patch; it's being replaced by some changes in R2API, which will also require some changes in Hailstorm and Umbrella.  It won't be functional until both R2API and these mods are updated.

**Comment by pO0P3R125** [comment]
welll, its a shame, this is my favorite mod, thanks for the reply
