### ISSUE TITLE
Pressing shortcuts while in chat or in the game menu triggers events or errors

### ISSUE THREAD

**Issue by ghost** [Jarlyk/JarlykMods#22]

**Comment by ghost** [comment]
Fixe ;
bool isInChatBox = false;
            On.RoR2.UI.ChatBox.FocusInputField += (orig, self) => { orig(self); isInChatBox = true; };
            On.RoR2.UI.ChatBox.UnfocusInputField += (orig, self) => { orig(self); isInChatBox = false; };
Then check isInChatBox after each GetKeyDown

**Comment by Jarlyk** [comment]
Fixed and will be in 1.0 release
