### ISSUE TITLE
default shortcut for startpack is equivalent to configuration manager shortcut

### ISSUE THREAD

**Issue by harbingerofme** [Jarlyk/JarlykMods#23]
both are bound to f1

**Comment by Jarlyk** [comment]
I've debated whether I should change this.  On the one hand, keeping the default consistent will ease users transitioning into the new version.  On the other hand, a fairly large proportion of people may end up using the configuration manager eventually, so the conflict is likely to come up and users would either have to change the default keybinding or put up with the config screen also showing up.

**Comment by Jarlyk** [comment]
Leaving default as-is for now
