### ISSUE TITLE
[EliteSpawningOverhaul] Normal enemies inherit elites' health

### ISSUE THREAD

**Issue by MightyW0lf** [Jarlyk/JarlykMods#38]
Normal enemies spawned along with the elite enemies inherit health of the elite. I.e. all enemies spawned with the elite have the same health as the elite.

On [this preview](https://youtu.be/Shb0gErj_Tc) you can see an Overloading Beetle which spawned with a bunch of normal Beetles. Shortly after, some normal Beetles spawned by themselves. Notice the Beetles spawned along with the Overloading one not dying instantly, while the ones spawned by themselves die to a single Captain's M1.

EliteSpawningOverhaul version: 1.0.0
The only additional mod in the video is DebugToolkit v3.4.0 for easier reproduction. Bug appears without this mod as well.

**Comment by Jarlyk** [comment]
Hmm, interesting.  I think the game is actually probably trying to spawn them all as Overloading, but ESO applied the elite boosts without actually applying the equipment for the elite affix.  I'll have to dig into how the spawning works with squads.

**Comment by Jarlyk** [comment]
Thanks for the report; fixed in v1.0.1
