### ISSUE TITLE
ESO: Exception in late game?

### ISSUE THREAD

**Issue by Jarlyk** [Jarlyk/JarlykMods#63]
Report from breadguy on the Discord.  

Review of log suggests that ESO is the only mod hooking this method, so it's very likely a bug in ESO.  Since it's happening very late game, possibly the OnCardSpawned is somehow being called with a null SpawnResult due to not being able to spawn?

---------------------------------

 im getting this error again, im almost certain its ESO:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.CombatDirector+<>cDisplayClass72_0.<AttemptSpawnOnTarget>gOnCardSpawned|0 (RoR2.SpawnCard+SpawnResult result) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
RoR2.SpawnCard.DoSpawn (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, RoR2.DirectorSpawnRequest spawnRequest) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
RoR2.DirectorCore.TrySpawnObject (RoR2.DirectorSpawnRequest directorSpawnRequest) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
RoR2.CombatDirector.AttemptSpawnOnTarget (UnityEngine.Transform spawnTarget, RoR2.DirectorPlacementRule+PlacementMode placementMode) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
RoR2.CombatDirector.Simulate (System.Single deltaTime) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
RoR2.CombatDirector.FixedUpdate () (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
Attachment file type: document
message.txt
22.54 MB
only happens when things start to get really hectic
like when mobs hit spawn cap
hailstorm is the only eso dependent mod i have also
also this is getting spammed and i dont know why:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.HealthComponent.ServerFixedUpdate () (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)
RoR2.HealthComponent.FixedUpdate () (at <b2a8f28d2811419eafa07a88f8c3d4bf>:0)

**Comment by sanity-dance** [comment]
I'm having the same issue, especially during teleporter fights on stage 4+ and in the late game. Here is the exception with IlLine installed:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.CombatDirector+<>c__DisplayClass72_0.<AttemptSpawnOnTarget>g__OnCardSpawned|0 (RoR2.SpawnCard+SpawnResult result) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:IL_000C)
RoR2.SpawnCard.DoSpawn (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, RoR2.DirectorSpawnRequest spawnRequest) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:IL_0037)
RoR2.DirectorCore.TrySpawnObject (RoR2.DirectorSpawnRequest directorSpawnRequest) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:IL_0172)
RoR2.CombatDirector.AttemptSpawnOnTarget (UnityEngine.Transform spawnTarget, RoR2.DirectorPlacementRule+PlacementMode placementMode) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:IL_0314)
RoR2.CombatDirector.Simulate (System.Single deltaTime) (at <b2a8f28d2811419eafa07a88f8c3d4bf>:IL_007E)
RoR2.CombatDirector.FixedUpdate () (at <b2a8f28d2811419eafa07a88f8c3d4bf>:IL_0066)

**Comment by Jarlyk** [comment]
Checked with the devs and there is likely a vanilla issue here, which is then exacerbated by mods that can cause a lot of spawns to occur.  I added a mitigation in ESO 1.2.2 which injects a null check to prevent the NRE spam when the spawn card chooses not to spawn anything.
